sonar.projectKey=taxi-service-auth
sonar.projectName=Taxi Service Auth
sonar.projectVersion=1.0

sonar.sources=TaxiService.Auth
sonar.tests=TaxiService.Auth.Tests

sonar.language=cs

sonar.cs.opencover.reportsPaths=TaxiService.Auth.Tests/coverage-results/**/coverage.cobertura.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000